"""rename department

Revision ID: 05deb2dcb097
Revises: e1f76366f357
Create Date: 2024-06-27 22:59:15.491905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05deb2dcb097'
down_revision = 'e1f76366f357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
